### ISSUE TITLE
More flexible accessors

### ISSUE THREAD

**Issue by derosm2** [madeintandem/jsonb_accessor#100]
One issue that's kept me from adopting this gem more widely is that I need to define all possible top level keys for a jsonb column. If I don't, then I will receive an `ActiveRecord::MissingAttributeError`. This removes much of the flexibility of having a jsonb column. For example when storing a JSON response from a webhook. The structure may be well defined, but if a new key is added then we'd get an error.

Ideally, any `given_value` sent to ["#{jsonb_attribute}="](https://github.com/devmynd/jsonb_accessor/blob/master/lib/jsonb_accessor/macro.rb#L70) would get written to the DB as is.

Would you be open to a PR for this? Anything else I should be aware of?

Thanks!

**Comment by haffla** [comment]
I know it's a long time ago but now that the gem is being maintained again, you are welcome to create a PR. I like the idea.

**Comment by caiohsramos** [comment]
This could be done with `method_missing` and `respond_to_missing?` right? Maybe it should be an opt-in/opt-out feature as someone may rely on `MissingAttributeError`

**Comment by haffla** [comment]
@caiohsramos I not sure but I think a simple check with `respond_to?` [here](https://github.com/madeintandem/jsonb_accessor/blob/master/lib/jsonb_accessor/macro.rb#L87) should suffice, I mean `next unless respond_to? name`.

The whole jsonb value is written 7 lines above already https://github.com/madeintandem/jsonb_accessor/blob/master/lib/jsonb_accessor/macro.rb#L87.

**Comment by caiohsramos** [comment]
@haffla right. Now I got the problem, seems pretty straight foward. Maybe I can give this one a try later

**Comment by alxppp** [comment]
Quick workaround that worked for me: `Model.find(xyz).update_column(:jsonb_column, {arbitrary_data: 'goes here'})`. This will bypass the dynamic attribute creation when writing, but still allow reading via `jsonb_accessor`
