### ISSUE TITLE
Method for Enumerating Accessor Fields

### ISSUE THREAD

**Issue by joshuamcginnis** [madeintandem/jsonb_accessor#101]
I'm looking for a list that enumerates the defined accessors on a jsonb column, not unlike `model_klass.new.attributes.keys` which returns all attributes for a model (jsonb accessors included).

Digging through the source, I found that the lib is creating a helper method that does almost exactly what I need via [`klass.jsonb_store_key_mapping_for_credit_attributes`](https://github.com/devmynd/jsonb_accessor/blob/master/lib/jsonb_accessor/macro.rb#L18)? 

Is it safe to use this method in production? Would it be useful to expose a more user-friendly and tested public api for enumerating the defined accessors?

In my use-case, I'm creating a lot of records using these accessors and for this task, my database returns the exact same accessor names as the ones I've defined in my model. With this helper method, I can simply loop through all the fields to do value assignment, as opposed to having to explicitly set each field ala `.new(a: result[:a], b: result[:b], ...)`. 

Thanks.

**Comment by rickychilcott** [comment]
I have this need too. I'd like to dynamically generate an admin interface based on the jsonb_fields.

I can get by with using `jsonb_store_key_mapping_for_#{name}`, but it'd be nice if there was a version with contained the field name and the type.

This is a public method, so I guess it appears to be OK to use it. There is a [spec for it](https://github.com/devmynd/jsonb_accessor/blob/d31ce5cc9391022819d757a9dde07b4cf98581d6/spec/jsonb_accessor_spec.rb#L482)

This may meet my needs (not tested) yet.

```ruby
jsonb_attributes_method_name = "jsonb_attributes_for_#{jsonb_attribute}"
# Defines methods on the model class
class_methods = Module.new do
  # Allows us to get a mapping of field names to store keys scoped to the column
  define_method(jsonb_attributes_method_name) do
    superclass_mapping = superclass.try(jsonb_attributes_method_name) || {}
    superclass_mapping.merge(field_types)
  end
end
```

**Comment by rickychilcott** [comment]
This brings up a good question, is anyone maintaining this?
