### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by TomaszKot11** [madeintandem/jsonb_accessor#103]
`DEPRECATION WARNING: Dangerous query method (method whose arguments are used as raw SQL) called with non-attribute argument(s): "(events.event_data -> 'changed_at') asc". Non-attribute arguments will be disallowed in Rails 6.0. This method should not be called with user-provided values, such as request parameters or model attributes. Known-safe values can be passed by wrapping them in Arel.sql().`. 

How about updating to Rails 6.0?

**Comment by zokioki** [comment]
There's a [PR](https://github.com/madeintandem/jsonb_accessor/pull/107) for addressing this, hopefully it gets some more eyes on it soon 👍

**Comment by stephanieminn** [comment]
closing because https://github.com/madeintandem/jsonb_accessor/pull/107 is merged!
