### ISSUE TITLE
What is the best way to move jsonb_accessor into a concern?

### ISSUE THREAD

**Issue by dark88888** [madeintandem/jsonb_accessor#106]
Hi,

I'm using jsonb_accessor in my project and the model is pretty big now. 
Is there a way to move all code related to the jsonb_accessor to a concern?

Thank you very much!

**Comment by haffla** [comment]
Of course this is possible.

```
module Bla
  extend ActiveSupport::Concern
  included do
    jsonb_accessor :properties, name: :string
  end
end

class Something < ApplicationRecord
  include Bla
end
```

Please close the issue.
