### ISSUE TITLE
Not able to change the jsonb field shows no class method found

### ISSUE THREAD

**Issue by abhiyan52** [madeintandem/jsonb_accessor#109]
u.affiliate_manager = 10 .....
NoMethodError (super: no superclass method `affiliate_manager=' for #<User:0x00005637bf61bf00>)

**Comment by abhiyan52** [comment]
It is taking method along with '='

**Comment by haffla** [comment]
@abhiyan52 could you describe in more detail the problem? Please show how you have defined `jsonb_accessor` on your model.

**Comment by haffla** [comment]
@abhiyan52 feel free to reopen with a detailed description on how to reproduce this issue.

**Comment by abhiyan52** [comment]
It has been already 2 years and I am not working in Ruby anymore. I also donot remeber what was the exact issue.
