### ISSUE TITLE
Avoid writing all keys with null

### ISSUE THREAD

**Issue by n00ge** [madeintandem/jsonb_accessor#110]
Is it possible to avoid writing all keys defined in the `jsonb_accessor` to the database as null when they haven't been defined? For a busy table it feels expensive to store all of that.

**Comment by justi** [comment]
At this moment I use something like compact! in before_save callback on fields that are declared as jsonb_accessor

**Comment by haffla** [comment]
@n00ge I just tested this and it seems that this is not an issue anymore.
