### ISSUE TITLE
Multiple Columns

### ISSUE THREAD

**Issue by Kaakati** [madeintandem/jsonb_accessor#111]
The store_accessor will allow to have a prefix to your data, to be able to differentiate in case you have similar names, in my case I have `origin` & `destination` which both have `latitude` & `longitude`, currently they're overlapping each others.

- Is there a way to have a prefix?
- Is there a way to handle JSONB Array ?

**Comment by haffla** [comment]
You can implement this using `store_key`:

```
# your first column
jsonb_accessor :destination,
  destination_latitude: [:string, store_key: 'latitude'],
  destination_longitude: [:string, store_key: 'longitude']

# your second column
jsonb_accessor :origin,
  origin_latitude: [:string, store_key: 'latitude'],
  origin_longitude: [:string, store_key: 'longitude']
```
