### ISSUE TITLE
Is the library supported?

### ISSUE THREAD

**Issue by Miroshni4enko** [madeintandem/jsonb_accessor#112]
According to the last commit that was committed Aug 26, 2017, I wonder is the library supported for now?

**Comment by OneDivZero** [comment]
Would be good to know :-)

**Comment by wynksaiddestroy** [comment]
There is a similar Gem that seems to be actively maintained: https://github.com/DmitryTsepelev/store_model
I haven't tried it yet, because I'm still figuring out which one to use.

**Comment by thegrubbsian** [comment]
Hey all, the Tandem team is just getting back to this library after a hiatus where we didn't have anyone owning it.  We will be working on issue resolution and merging some pull requests over the next few weeks.  Keep an eye out for updates.
