### ISSUE TITLE
Uniqueness validation doesn't work

### ISSUE THREAD

**Issue by rabidaudio** [madeintandem/jsonb_accessor#113]
```rb
class Foo < ApplicationRecord

  jsonb_accessor :data, unique_string: :string

  validates :unique_string, uniqueness: true
end

Foo.create!(unique_string: 'abcd') # => raises ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column foos.unique_string does not exist)
```
It would seem the uniqueness validator is assuming `unique_string` is a column and not a jsonb property. This is in Rails 6.0.2.1. 

As a workaround, building a validator manually works:

```rb
class Foo < ApplicationRecord

  jsonb_accessor :data, unique_string: :string

  # validates :unique_string, uniqueness: true
  validate :unique_string_uniqueness

  protected

  def unique_string_uniqueness
    if Foo.data_where(unique_string: unique_string).where.not(id: self).exists?
      errors.add(:unique_string, 'must be unique')
    end
  end
end
```

**Comment by haffla** [comment]
I don't think this is something this gem should take care of and you have demonstrated yourself how it could be implemented using Rails. BTW also in Postgresql it is not possible to define a unique index on a jsonb field.

**Comment by dchacke** [comment]
Just for reference, from the [docs](https://api.rubyonrails.org/classes/ActiveRecord/Store.html):

> NOTE: The default validations with the exception of `uniqueness` will work. For example, if you want to check for `uniqueness` with `hstore` you will need to use a custom validation to handle it.
