### ISSUE TITLE
How to use jsonb_accessor scopes on join associations

### ISSUE THREAD

**Issue by coisnepe** [madeintandem/jsonb_accessor#119]
Hi,

After a few minutes spent trying to figure out how to use a `jsonb_accessor` scope on a join I finally remembered about the `.merge` method.
Do you think it would be useful to add a few lines and an example to show how to achieve this?

Something like:

```ruby
# Returns all the users that have at least one product reviewed and displayable
User
  .joins(:products)
  .where(products: { displayable: true })
  .merge(Product.data_where_not(reviewed_at: nil))
```

**Comment by haffla** [comment]
Hm since `data_where_not` just calls Rails's `where` under the hood, for me it's pretty obvious that `jsonb_accessor` works with `merge`, too.

**Comment by milushov** [comment]
@coisnepe, thank you! It's not obvious
