### ISSUE TITLE
Ruby 2.7 deprecation warning

### ISSUE THREAD

**Issue by jacobjlevine** [madeintandem/jsonb_accessor#125]
Relevant stack/libraries:
jsonb_accessor - 1.0.0
Rails - 6.0.3.1
Ruby - 2.7.1

Loading my application since upgrading to Ruby 2.7 yields the following warning message:
lib/jsonb_accessor/macro.rb:14: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call

**Comment by haffla** [comment]
This is solved in #128. I am waiting for approval.

**Comment by jacobjlevine** [comment]
@stephanieminn are you able to approve pull requests?

**Comment by jacobjlevine** [comment]
And/or give appropriate permissions to contributors like @haffla so they can merge their work into the main project (https://github.com/haffla/jsonb_accessor)

**Comment by haffla** [comment]
Hey thanks for this. @jacobjlevine I've also contacted @thegrubbsian (member of madeintandem) via email but didn't get no reply....

**Comment by haffla** [comment]
@crismali maybe? Seems to be the main author.
