### ISSUE TITLE
Is this gem being actively developed?

### ISSUE THREAD

**Issue by blizkreeg** [madeintandem/jsonb_accessor#126]
I've in the past used `jsonb_accessor` extensively but I don't see any new commits and see open PRs and issues that haven't been addressed. Is it a risk using this in a production app going forward?

**Comment by haffla** [comment]
I honestly have very similar concerns. Authors don't seem to be very responsive and seem to neglect issues and PRs. It's a shame.

**Comment by haffla** [comment]
Nothing, just nothing. No reaction.

**Comment by blizkreeg** [comment]
I think you can assume it's not being actively developed. I've stopped using it.

**Comment by haffla** [comment]
@crismali @sassygrody maybe you are looking for someone to maintain this gem? It's quite a shame.

**Comment by haffla** [comment]
For posterity, maintained better alternatives

https://github.com/DmitryTsepelev/store_model
https://github.com/jrochkind/attr_json

**Comment by joelvh** [comment]
@mercedesb are you open to making @haffla or others maintainers?

**Comment by mercedesb** [comment]
> @mercedesb are you open to making @haffla or others maintainers?

Yep, @haffla you have a pending invite. I am leaving this organization on Friday so you'll need to ping other maintainers for support and to make releases to ruby gems.

**Comment by haffla** [comment]
Nice! Thank you. What about releasing new versions? Could you somehow add me as a collaborator to RubyGems aswell?

**Comment by mercedesb** [comment]
> Nice! Thank you. What about releasing new versions? Could you somehow add me as a collaborator to RubyGems aswell?

I won't be able to. Right now I think you'll still need to ping a member of this organization to do that release.

**Comment by haffla** [comment]
> > Nice! Thank you. What about releasing new versions? Could you somehow add me as a collaborator to RubyGems aswell?
> 
> I won't be able to. Right now I think you'll still need to ping a member of this organization to do that release.

Oh dear. Yea pinging someone from this organization has proven to be very very difficult... like it took 6 months last time. Could you maybe raise awareness about this open source project before you leave your job?

**Comment by haffla** [comment]
OK I have write access to this repo now but am not able to release new versions....

**Comment by alec-c4** [comment]
@cainwatson could you please assist @haffla with access to rubygems?

**Comment by alec-c4** [comment]
@haffla i think you better to fork this repo and publish code as a new gem :)

**Comment by haffla** [comment]
@alec-c4 a lot of people are already using this gem. A fork on Rubygems would require a renaming. I don't think it's worth it. I would prefer if madeintandem gave me access to the RubyGems account as a maintainer or something like that.

**Comment by haffla** [comment]
Amazing thank you. I have just released v1.3.0. I guess this issue can be closed now.

**Comment by greghaygood** [comment]
Hey @haffla - Congrats on taking on this project! I'm looking to use it for a project that's developed the need for this kind of flexibility, and saw this issue during my due diligence. So please forgive the comment on a closed ticket, but perhaps it will help others in a similar situation. 

I looked at the alternatives you suggested above, but the API of this one feels much cleaner and thus would prefer to use it. So I just wanted to check if you're planning to "mind the shop" (as far as any open source maintainer can predict such support, of course!). Thanks!

**Comment by blizkreeg** [comment]
Curious if there was a bounty system attached to maintaining/fixing open source projects, we'd see more better support. I know that's not the primary motivation of most folks contributing to open source, but there are only 24h in a day, and sometimes incentives help :)

sorry, a bit off topic.

**Comment by haffla** [comment]
@greghaygood yes I am intending to maintain this project long term. I am using it myself in several Rails projects. Also messages like yours motivate me even more :)
