### ISSUE TITLE
If a column is NULL post migration, but there's a default accessor, it is still returned as nil

### ISSUE THREAD

**Issue by tfmertz** [madeintandem/jsonb_accessor#136]
Maybe this is unavoidable, but I'll share a recent scenario.

We added a jsonb_accessor
```ruby
User < ApplicationRecord
  jsonb_accessor :overrides, test: [:boolean, default: false]
end
```

and a migration:

```ruby
class AddOverridesToUser < ActiveRecord::Migration[6.0]
  def change
    change_table :users do |t|
      t.jsonb :overrides
    end
  end
end
```

After the code was pushed up to staging, `User.first.overrides => nil` because that new column is NULL. Even though the default is set to false.

It makes sense why it's happening, it'd just be sweet if the accessor could handle returning defaulted values, even if the column was NULL or that default values was missing from the column data, that'd save a lot of migration shenanigans for new fields or updating accessors.

This is sort of related to #74 but the opposite. Instead of setting defaults when they don't exist on create, it would be retrieving the defaults from a column when they don't exist.

Or all of this is incorrect and there's a better way, definitely open to being enlightened😄

**Comment by haffla** [comment]
Hello @tfmertz. Thanks for reporting this. Just to clarify. `User.first.test` still returns `false` in your case right?

So what would you `User.first.overrides` expect to return? `{ "test" => false }`?

**Comment by tfmertz** [comment]
Oh wow, we're not running 1.3.2 in the Gemfile.lock, let me update and make sure this hasn't been solved. Thanks for your quick reply.

To clarify `User.first.overrides.test` gives us an error because `User.first.overrides` is nil. I haven't tested `User.first.test` I didn't know you could reference the json keys without the parent, but I will try that as well.

**Comment by tfmertz** [comment]
Ah ha! Yes, so we can reference the json key _inside_ the overrides column, and when the column is NULL is does return the correct default value of false for `User.first.test` even if `User.first.overrides` is `nil`.

Maybe this is working as intended, but we expected `User.first.overrides` to return `{ test: false}` even though the column was NULL. Our actual use case was a little more complex where we were looping through keys on `User.first.overrides` and that's why we ran into this issue.

If this isn't a true issue and doesn't warrant a fix, we could change our code to manually check each key, it'd just be more tedious, but totally doable.

**Comment by haffla** [comment]
Even if `overrides` is not nil `User.first.overrides.test` would raise an error because `overrides` is a simple hash which doesn't respond to a method `test`.

`overrides` is just a normal Rails attribute like any other and somehow I don't see it as this gem's responsibility to make sure it isn't nil. I am happy to merge a PR that changes this but I don't think it's a big issue now.
