### ISSUE TITLE
Query records based on provided array

### ISSUE THREAD

**Issue by sasharevzin** [madeintandem/jsonb_accessor#147]
Hi guys,

I'm trying to get all users based on `admin` or `editor` roles.

The User model has:
```
jsonb_accessor :properties, role: :string
```

I can get users by writing a custom query 
``` 
User.where("properties->'role' ?| array['admin', 'editor']")
```

Is there a way to do the same with `jsonb_accessor` that will generate `?|` operator?

Thank you.

**Comment by haffla** [comment]
Hey @sasharevzin,

`jsonb_accessor` adds a lot of useful finder methods as described [here](https://github.com/madeintandem/jsonb_accessor#scopes). But I think in this case you're out of luck and you must write your own. You could write it like this though:

```ruby
User.properties_where(role: 'admin').or(User.properties_where(role: 'editor'))
```

**Comment by sasharevzin** [comment]
Thank you, @haffla. I'll use `.or`
