### ISSUE TITLE
Assigning undefined jsonb values overwrites non-jsonb values in v1.3.3 

### ISSUE THREAD

**Issue by yurikoval** [madeintandem/jsonb_accessor#148]
v1.3.3 seems to have broken attribute assignment for values that are not defined in jsonb.
If you happen to have a key that has the same name as an attribute (non-jsonb) in ActiveRecord, it ends up overwriting it.
Expected behaviour would be to store the data, but not overwrite non-jsonb attributes. 

```ruby
create_table "products" do |t|
  t.jsonb "data"
end

class Product < ActiveRecord::Base
  jsonb_accessor :data, title: :string
end
```

```ruby
product = Product.new
product.created_at # nil
product.data = {title: "hello world", created_at: 1.year.ago}
product.title # "hello world"
product.created_at # "2021-08-19T15:40:42+08:00" (this should be nil)
```

**Comment by haffla** [comment]
Hello @yurikoval,

thanks for reporting this. I believe this bug had existed in v1.3.3 and before.

I've released v1.3.5 that fixes the issue.
