### ISSUE TITLE
Array on toplevel

### ISSUE THREAD

**Issue by Lapizistik** [madeintandem/jsonb_accessor#156]
I have a jsonb field that basically looks like this:
```
[{ foo: 'bar' }, { foo: 'baz', a: 3 }, {…}]
```
i.e. the top level type is an array.
This gem assumes to have a hashmap at toplevel.
Are there any plans to target this or is my design so unusual?

Thanks for your work!

**Comment by haffla** [comment]
Hello @Lapizistik,

I believe the main purpose of this gem is that you can store many different, even unrelated, things in one database field. If you have an array at the top level then that's the only thing you can store in this field.

I am afraid there aren't any plans to target this.

**Comment by Lapizistik** [comment]
Ok, I understand.
I need to store a collection of rather unrelated things ;-)
It would have been nice to be able to use the `where`-helpers for access instead of writing 
`MycModel.where('data @> ?', [{foo: "baz"}].to_json)`
but I understand if you don't want the additional complexity, so I'll roll something on my own.
I'll use your nice work for my other jsonb fields anyway.

Thanks a lot for your work and the quick response.
