### ISSUE TITLE
gem release 1.3.8-java is invalid

### ISSUE THREAD

**Issue by ashkulz** [madeintandem/jsonb_accessor#164]
If you compare the dependencies of [1.3.7-java](https://rubygems.org/gems/jsonb_accessor/versions/1.3.7-java) vs [1.3.8-java](https://rubygems.org/gems/jsonb_accessor/versions/1.3.8-java) they're different in `pg` vs `activerecord-jdbcpostgresql-adapter`.

I guess @haffla forgot to [build the `-java` gem on JRuby](https://github.com/madeintandem/jsonb_accessor/pull/157#issuecomment-1367196215), but I'm not sure what really happened :man_shrugging:

**Comment by haffla** [comment]
Hey @ashkulz sorry. I actually did build the gem for Java and pushed. I did `gem build --platform java`. But that's not enough apparently. Of course I need to do that using jruby. I had forgotten exactly how to do it.

Please check https://rubygems.org/gems/jsonb_accessor/versions/1.3.10-java. Let me know if that works.

I've create a script for building for both platforms now.

**Comment by ashkulz** [comment]
Thanks, looks good to me @haffla! As ever, thanks for the fast turnaround :clap:

**Comment by ashkulz** [comment]
@haffla can you release jsonb_accessor 1.3.10 (regular version)? Dependabot is confused because only one is released and not the other:

![Screenshot 2023-05-31 at 10-18-21 Bump jsonb_accessor from 1 3 8 to 1 3 10 by dependabot · Pull Request #7095 · teamsimplepay_simplepay](https://github.com/madeintandem/jsonb_accessor/assets/854352/68e6ab19-f4ee-42f9-a04c-fbb0fd3c019c)

**Comment by haffla** [comment]
Aiaiaiai, fixed now :)

**Comment by ashkulz** [comment]
Thanks, confirm that it works :tada:
