### ISSUE TITLE
Rails 7.1 breaks enum functionally

### ISSUE THREAD

**Issue by pabse** [madeintandem/jsonb_accessor#167]
I think that Rails 7.1 breaks the enum functionally with this gem.

It seems to be this commit: https://github.com/rails/rails/commit/6c5fab0668c1872fe827507f45ef400a20e8c646 

When I have a User model containing:

```ruby
jsonb_accessor :user_data, gender: :string

enum gender: { male: 'male', female: 'female' }
```

I'm getting an error: `Unknown enum attribute 'gender' for User (RuntimeError)`

Is there a possible solution for this?

**Comment by haffla** [comment]
Hi.

> Is there a possible solution for this?

I don't think there is. At least not without some serious monkey-patching that basically reverts this check in Rails.

**Comment by haffla** [comment]
@pabse since AR 7.1 dropped support for this, the next version of this gem will also drop support for it. No other option.

https://github.com/madeintandem/jsonb_accessor/pull/170

**Comment by davidwessman** [comment]
@haffla 
Just want to let you know that it will be available again:
https://github.com/rails/rails/pull/49769

**Comment by haffla** [comment]
Yep I've seen it. Thanks. I merely disabled the test for Rails 7.1 in the last release. I will enable it for Rails versions that support enums not backed by a column.
