### ISSUE TITLE
collection.pluck

### ISSUE THREAD

**Issue by owen2345** [madeintandem/jsonb_accessor#174]
Hi,

Is there a way to run `User.all.pluck(:phones)`? where `phones` is an array part of `data` as `jsonb` column

**Comment by haffla** [comment]
No this is not possible. Please look at the SQL that `pluck` is generating. 

```SQL
select users.phones from users;
```

You might wanna try `User.pluck(Arel.sql("data->'phones'"))`.

Anyway. Please do not open issues for general questions. For this I recommend StackOverflow.
