### ISSUE TITLE
Question: Is the gem compatible with custom setters

### ISSUE THREAD

**Issue by arturoherrero** [madeintandem/jsonb_accessor#179]
## Description

This question is not an issue, but I want to confirm what I suspect.

It looks like jsonb_accessor is not compatible with custom setters, so we cannot do something like the following because the gem overrides any other setter:

```ruby
jsonb_accessor :elasticsearch,
  :elasticsearch_url: string

def elasticsearch_url=(values)
  # This code is not executed
  ...
end
```

@haffla Is that correct?

**Comment by haffla** [comment]
Hi @arturoherrero, I just tested it myself and it works. 

```
  jsonb_accessor :extra_data, ch: :string

  def ch=(value)
    pp "Hi I am being called with #{value}"
    super
  end
```

**Comment by arturoherrero** [comment]
I'm confused now. I'm working on this GitLab issue https://gitlab.com/gitlab-org/gitlab/-/issues/500267, and the model is huge, so I have to figure out what's going on. I'll keep you posted. Thanks!

**Comment by haffla** [comment]
Good luck!

Just FYI the ability to override the setters is by design: https://github.com/madeintandem/jsonb_accessor/blob/master/lib/jsonb_accessor/macro.rb#L62

**Comment by arturoherrero** [comment]
I've also tested that with a different attribute and it's working as expected. I still have to figure out what's going on with the field not updated, but that's a separate problem. We can close this issue. Thanks for the feedback!
