### ISSUE TITLE
[Feature] Enum support

### ISSUE THREAD

**Issue by Epigene** [madeintandem/jsonb_accessor#87]
Hi!

I am interested in developing a sort of enum support for jsonb fields.

The use case:
  A JSONB field key should be allowed to have one of a predefined set of (string) values.

Pseudocode of DSL:

```rb
class Product
  jsonb_accessor :data,
    status: [:string, enum: [:available, :en_route, :unavailable], default: :available]   
end

p = Product.new
p.status #=> "available"
p.status = "en_route" #=> "en_route"
p.status #=> "en_route"
p.data
#=> {
  "status" => "en_route"
}

p.status = "discontinued" #=> RuntimeError, status "discontinued" not supported, try [:available, :en_route, :unavailable].
```

Does this sound like something that would get added to this gem were I to make a PR?

**Comment by abhiyan52** [comment]
Hey what is the status of this feature?

**Comment by preetsethi** [comment]
I tried this:
```

**Comment by haffla** [comment]
As @preetsethi has demonstrated this works prefectly fine.
