### ISSUE TITLE
jsonb array?

### ISSUE THREAD

**Issue by adambedford** [madeintandem/jsonb_accessor#88]
Is there support for having a jsonb array, rather than a hash? i.e. configuration such as 

```
jsonb_accessor :data, array: true
```

**Comment by full-of-foo** [comment]
This would be great to have.

**Comment by haffla** [comment]
Hmm `jsonb_accessor` is all about storing multiple different attributes (strings, integers, arrays, dates) in one jsonb field. If all you want is a jsonb array, you don't need this gem. You could just use standard Rails.

For array support within the hash use

```
jsonb_accessor :data, some_field: [:jsonb, array: true]
```

Now you can store anything in that array.

`the_model.update(some_field: [1, 2, '3', { k: 4 }]`)
