### ISSUE TITLE
Nested json with default value

### ISSUE THREAD

**Issue by tuykin** [madeintandem/jsonb_accessor#90]
Thank you for creating such a cool gem! Really like it!

My use case is described below:
I've got `User` with some feature flags. I've decided to store them in `metadata:jsonb` field as:
```
class User < ApplicationRecord
  jsonb_accessor :metadata, features: :json
end
```
to use it as 
```
user.features['some_cool_feature_enabled'] = true
...
```
It work perfect, except handling default value:
```
class User < ApplicationRecord
  jsonb_accessor :metadata, features: :json, default: {}
end
```
doesn't handle default value and returns `nil`

**Comment by dinshaw** [comment]
Just started using this gem. If you follow the syntax in the docs it works:
```ruby
 jsonb_accessor :metadata, features: [:json, default: {}]
```

**Comment by haffla** [comment]
Yes this works as @dinshaw has demonstrated.
