### ISSUE TITLE
Is there a scope to check whether the key is available in the jsonb?

### ISSUE THREAD

**Issue by mijoharas** [madeintandem/jsonb_accessor#91]
if I have:

```
jsonb_accessor :foobar, baz: :boolean
```

There are 4 cases, if the key is present then the value can one of `[true, false, nil]` (or `NULL` in postgres terms), there is also the case that the key is not present in the `jsonb` column. Is there a scope where I can query for this with your gem? (I've been dropping down to straight postgres when I've needed this).

**Comment by haffla** [comment]
Right now there isn't a scope for that. Feel free to create a PR. Closing now for inactivity of this issue thread. Feel free to reopen.
