### ISSUE TITLE
Bug with store_key & existing attribute

### ISSUE THREAD

**Issue by kshnurov** [madeintandem/jsonb_accessor#92]
Let's say we have a `Product` with `title` and `data`, containting another title:
```
class CreateProducts < ActiveRecord::Migration
  def change
    create_table :products do |t|
      t.string :title, null: false
      t.jsonb :data
    end
  end
end
class Product < ActiveRecord::Base
  validates :title, presence: true
  jsonb_accessor :data,
    data_title: [:string, store_key: 'title']
end
```
Everything seems to work:
```
p = Product.new( title: 'Real title', data_title: 'Data title')
p.title # Real title
p.data_title # Data title
p.data # {"title"=>"Data title"}
```
Until we call save or update:
```
p.save
p.title # Data title
p.data_title # nil
p.data # {"title"=>nil,""=>"Data title"}
p.save # ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "title" violates not-null constraint
p.title # nil
p.data_title # nil
p.data # {"title"=>nil,""=>nil}
p.update( title: 'Real title' ) # ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "title" violates not-null constraint
```
Rails 5.1.4, jsonb_accessor 1.0.0
This looks like a serious bug, even validation on `title` is passed, but `data_title` is written into DB instead of `title`. I've looked through the sources and didn't found a reason for this. Hope you can help.

**Comment by jylinman** [comment]
I encountered this too.  I ran into this by storing a payment object from a webhook that had a key named "id" and my model also has an "id".  I was doing the following 

```ruby
jsonb_accessor :data, customer_id: [:string, store_key: :id]
```

Whenever I would save it would throw an error saying there was a duplicate key entry or a foreign key exception.

**Comment by haffla** [comment]
I have just tested this and looks like this is not an issue anymore.
