### ISSUE TITLE
dirty checking inconsistency

### ISSUE THREAD

**Issue by mockdeep** [madeintandem/jsonb_accessor#95]
I'm working on a tool that makes use of dirty tracking in ActiveRecord, and came across an inconsistency with `jsonb_accessor`. I've got a model that looks like:

```rb
class Feedback < ApplicationModel
  jsonb_accessor :data, easy: [:boolean, default: false]
end
```

When I assign via the `#easy` method, it works about like I'd expect, showing both `data` and `easy` as changed:

```irb
> feedback.easy = 'true'
=> "true"
> feedback.changed
=> ["data", "easy"]
```

But when I use hash assignment syntax, it only shows `easy` as changed:

```irb
> feedback['easy'] = true
=> true
> feedback.changed
=> ["easy"]
```

For normal database attributes, it works the same both ways.

This is a little problematic for me as I'm [trying to bulk update records](https://github.com/thread-pond/junk_drawer/blob/master/lib/junk_drawer/rails/bulk_updatable.rb) by inspecting the changed attributes. I can probably find a workaround, but thought I'd post this here to see if there's any chance for a fix.

Thanks for the handy library!

**Comment by haffla** [comment]
OK as @mockdeep pointed out, seems to be an AR issue. Feel free to reopen.
